function login(){if(document.getElementById("adminPass").value==="12345"){sessionStorage.setItem("nq_admin","1");document.getElementById("loginBox").style.display="none";document.getElementById("panel").style.display="block";loadAdmin()}else document.getElementById("loginMsg").textContent="پاسورډ ناسم دی."}
function showTab(id){document.querySelectorAll(".tab").forEach(x=>x.style.display="none");document.getElementById(id).style.display="block";if(id==="students")renderStudents();if(id==="coursesTab")renderCourses()}
function loadAdmin(){let d=JSON.parse(localStorage.getItem("nq_settings")||"null")||{name:"نور القرآن اسلامي اکاډمي",hero:"",about:"",contact:"",courses:[]};document.getElementById("sName").value=d.name;document.getElementById("sHero").value=d.hero;document.getElementById("sAbout").value=d.about;document.getElementById("sContact").value=d.contact;renderCourses()}
function saveSettings(){let d=JSON.parse(localStorage.getItem("nq_settings")||"null")||{courses:[]};d.name=document.getElementById("sName").value;d.hero=document.getElementById("sHero").value;d.about=document.getElementById("sAbout").value;d.contact=document.getElementById("sContact").value;localStorage.setItem("nq_settings",JSON.stringify(d));document.getElementById("saveMsg").textContent="معلومات ذخیره شوه. Website بیا خلاص کړئ."; }
function addCourse(){let d=JSON.parse(localStorage.getItem("nq_settings")||"null")||{name:"نور القرآن اسلامي اکاډمي",hero:"",about:"",contact:"",courses:[]};let c={title:document.getElementById("cTitle").value,desc:document.getElementById("cDesc").value,fee:document.getElementById("cFee").value,live:document.getElementById("cLive").value,video:document.getElementById("cVideo").value};if(!c.title)return;d.courses.push(c);localStorage.setItem("nq_settings",JSON.stringify(d));["cTitle","cDesc","cFee","cLive","cVideo"].forEach(id=>document.getElementById(id).value="");renderCourses()}
function renderCourses(){let d=JSON.parse(localStorage.getItem("nq_settings")||"null")||{courses:[]};let el=document.getElementById("adminCourses");if(!el)return;el.innerHTML=d.courses.map((c,i)=>`<div class="card"><h3>${c.title}</h3><p>${c.desc}</p><b>${c.fee}</b><br><button class="smallbtn danger" onclick="deleteCourse(${i})">حذف</button></div>`).join("")}
function deleteCourse(i){let d=JSON.parse(localStorage.getItem("nq_settings"));d.courses.splice(i,1);localStorage.setItem("nq_settings",JSON.stringify(d));renderCourses()}
function renderStudents(){let s=JSON.parse(localStorage.getItem("nq_students")||"[]"),el=document.getElementById("studentTable");if(!s.length){el.innerHTML="<p>تر اوسه کوم زده‌کوونکی ثبت شوی نه دی.</p>";return}el.innerHTML="<table><tr><th>نوم</th><th>شمېره</th><th>ژبه</th><th>کورس</th><th>وخت</th><th>حالت</th></tr>"+s.map((x,i)=>`<tr><td>${x.name}</td><td>${x.phone}</td><td>${x.language}</td><td>${x.course}</td><td>${x.time||"-"}</td><td><button class="smallbtn" onclick="approve(${i})">${x.status}</button></td></tr>`).join("")+"</table>"}
function approve(i){let s=JSON.parse(localStorage.getItem("nq_students")||"[]");s[i].status="Approved";localStorage.setItem("nq_students",JSON.stringify(s));renderStudents()}
function exportStudents(){let s=JSON.parse(localStorage.getItem("nq_students")||"[]");let rows=[["Name","Father","Phone","Age","Gender","Language","Course","Time","Status","Date"],...s.map(x=>[x.name,x.father,x.phone,x.age,x.gender,x.language,x.course,x.time,x.status,x.date])];let csv=rows.map(r=>r.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n");let a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}));a.download="noor-al-quran-students.csv";a.click()}
if(sessionStorage.getItem("nq_admin")==="1"){document.getElementById("loginBox").style.display="none";document.getElementById("panel").style.display="block";loadAdmin()}